### ISSUE TITLE
 Collect images from the actual device

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/tinyCAML#1]
collect atleast 50 images of each class (water/ no water)

**Comment by Bolewitz** [comment]
Set the ESP32-CAM to capture photos overnight. This morning I found out that it will only count up to 256 images before it rolls over and starts rewriting at image 1. This is because the pictureNumber is stored in the EEPROM using one byte, so it can only have values from 0-255. 
Going to try and change pictureNumber to a long so it can hopefully capture as many images as we need. 
https://github.com/UNCG-DAISY/tinyCAML/commit/ff792889b69229f333f32dddbd2660fe8ee1e243

**Comment by Bolewitz** [comment]
- [x] Good QVGA quality
- [x] Low-light functionality
- [ ] Fix quality for high contrast scenes
- [ ] Fix purple tint/purple lines

Added low-light functionality with [8d1b765](https://github.com/UNCG-DAISY/tinyCAML/commit/8d1b765fd94523a0e62e9598295b020abaf641dc). Need to address the quality issues for high contrast scenes, and the issues with the purple tint/purple lines.
Purple tint may be caused by some of the white balance parameters. 
Purple lines may be caused by a power issue with the board or the OV2640.

**Comment by anardek** [comment]
> * [x]  Good QVGA quality
> * [x]  Low-light functionality
> * [ ]  Fix quality for high contrast scenes
> * [ ]  Fix purple tint/purple lines
> 
> Added low-light functionality with [8d1b765](https://github.com/UNCG-DAISY/tinyCAML/commit/8d1b765fd94523a0e62e9598295b020abaf641dc). Need to address the quality issues for high contrast scenes, and the issues with the purple tint/purple lines. Purple tint may be caused by some of the white balance parameters. Purple lines may be caused by a power issue with the board or the OV2640.

From Evan: purple lines probably aren't a huge deal. Will probably make a more robust detector.

**Comment by Bolewitz** [comment]
@anardek when is the next possible time I can deploy the camera module in order to capture flooded/not_flooded images from the device?

**Comment by anardek** [comment]
Not sure. We're waiting on some sensors from Hawaii that we need to install via the jetski. That's probably the best time.

**Comment by ebgoldstein** [comment]
will not be done in this repo - close via https://github.com/UNCG-DAISY/tinyCamML/commit/3ecf1e50c92de5706976845c6996e87409ce633f
